---
kind: pipeline
type: docker
name: default



clone:
  disable: true

steps:
- name: clone
  commands:
  - git clone https://github.com/snehakpersistent/test-project.git .

- name: greeting
  image: ubuntu:latest
  commands:
  - echo hello

trigger:
  branch:
  - main
